### PR TITLE
Create datastream for tracking similarity metrics

### PR DESCRIPTION
**Pull request by harrisonpim**
Updates the scripts for creating and updating the `metrics-conversion-prod` datastream so that users can also create/update the new `metrics-similarity-prod` datastream.

### CODE REVIEW

**Review by jamieparkinson — COMMENTED** [review]
Hmm - this seems fine, but especially now the reporting cluster is in Terraform I would quite like to see us using the Elasticstack Terraform provider where possible as these scripts are really hard to maintain. afaict all the necessary resources for this exist in [the provider](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs).

**Comment by harrisonpim** [comment]
ooh, that's very nice!

do you mind if we get this in for now and come back to migrate it over to tf?

**Review by jamieparkinson — APPROVED** [review]
Sure, but definitely let's make sure it gets done

**Comment by harrisonpim** [comment]
part of https://github.com/wellcomecollection/wellcomecollection.org/issues/8885

**Pull request merged**
